import { type assetConfig } from "./three/types";

const assets = {
  bg: '/bg.png',
  bgBack: '/bg-back.png',
  pin: '/pin.png',
  hat: '/hat.png',
  canvas: '/canvas.png',
  creative: '/creativec.png',
  design: '/design.png',
  math: '/math.png',
  motion: '/motion.png',
  threejs: '/threejs.png',
  webgl: '/webgl.png',
  name_card: '/name_card.png',
  meidi: '/meidi.png',
  doubanzoo: '/douban-zoo.webm',
  screenshot: '/screenshot.png',
  area_title: '/area_title.png',
  edu_title: '/edu_title.png',
  projects_title: '/projects_title.png',
  techbox_title: '/techbox_title.png',
  work_title: '/work_title.png',
};

export const assetsConfig: assetConfig[] = [
  {
    src: assets.bg,
    back: assets.bgBack,
    displacementMapSrc: '/textures/paper-displacement.png',
    normalMapSrc: '/textures/paper-normal.webp',
    width: 800,
    displacementScale: 100,
    normalScale: 1.6,
    position: { x: 0, y: 0, z: -60 },
    roughness: 0.7,
  },
  { src: assets.pin, width: 100, position: { x: -340, y: 555, z: 10 }, roughness: 0.4 },
  { src: assets.hat, width: 195, position: { x: 165, y: 555, z: 12 }, rotation: { z: -Math.PI / 16 }, group: 'shaking' },
  { src: assets.name_card, width: 500, position: { x: 270, y: 480, z: 10 }, roughness: 0.4, rotation: { z: Math.PI / 60 } },
  { src: assets.area_title, width: 220, position: { x: -290, y: 460, z: 8 }, castShadow: false, },
  { src: assets.edu_title, width: 230, position: { x: 295, y: 250, z: 8 }, castShadow: false, },
  { src: assets.work_title, width: 395, position: { x: -205, y: 40, z: 8 }, castShadow: false, },
  { src: assets.projects_title, width: 190, position: { x: 310, y: -105, z: 8 }, castShadow: false, },
  { src: assets.techbox_title, width: 295, position: { x: -250, y: -385, z: 8 }, castShadow: false, },
  {
    src: assets.doubanzoo,
    coverSrc: assets.screenshot, width: 310, position: { x: 250, y: -410, z: 10 }, cornerRadius: 0.1, castShadow: false
  },
  { src: assets.meidi, width: 90, position: { x: 160, y: -125, z: 10 }, roughness: 0.4, href: "https://douban-zoo.github.io/" },
  { src: assets.webgl, roughness: 0.4, width: 100, position: { x: -90, y: -30, z: -2 }, group: 'stickers' },
  {
    src: assets.threejs,
    width: 100,
    position: { x: 0, y: 0, z: 6 },
    rotation: { z: -Math.PI / 20 },
    group: 'stickers',
    roughness: 0.4,
  },
  {
    src: assets.canvas,
    width: 100,
    position: { x: 100, y: 20, z: 2 },
    rotation: { z: -Math.PI / 60 },
    roughness: 0.4,
    group: 'stickers',
  },
  {
    src: assets.motion,
    roughness: 0.4,
    width: 120,
    position: { x: 50, y: 75, z: 4 },
    rotation: { z: Math.PI / 60 },
    group: 'stickers',
  },
  {
    src: assets.creative,
    width: 120,
    position: { x: -70, y: 50, z: 0 },
    rotation: { z: -Math.PI / 60 },
    group: 'stickers',
  },
  {
    src: assets.design,
    width: 130,
    position: { x: -30, y: -80, z: 3 },
    roughness: 0.4,
    rotation: { z: 0.1 },
    group: 'stickers',
  },
  { src: assets.math, width: 120, position: { x: 70, y: -60, z: 5 }, roughness: 0.4, group: 'stickers' },
];

export const SCENE_CONFIG = {
  cameraZ: 1350,
  designCameraZ: 800,
  shadowMapSize: 2048,
  shadowAreaSize: 1000,
};